-- Supabase-ready schema for AgroBrain360
-- Uses auth.users for authentication and a public profiles table
-- for app-specific user data.

create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  name varchar(100) not null,
  phone varchar(15) unique,
  email varchar(150) unique,
  language varchar(5) default 'en',
  region varchar(100),
  app_rating smallint,
  app_feedback text,
  app_feedback_updated_at timestamptz,
  created_at timestamptz default now(),
  is_active boolean default true
);

alter table if exists public.profiles
  add column if not exists app_rating smallint,
  add column if not exists app_feedback text,
  add column if not exists app_feedback_updated_at timestamptz;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'profiles_app_rating_check'
  ) then
    alter table public.profiles
      add constraint profiles_app_rating_check
      check (app_rating between 1 and 5 or app_rating is null);
  end if;
end
$$;

create table if not exists public.crop_scans (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  disease varchar(100) not null,
  confidence double precision not null,
  crop_type varchar(100),
  severity varchar(20),
  treatment text,
  image_path text,
  synced boolean default true,
  created_at timestamptz default now()
);

create table if not exists public.livestock_recs (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  animal_type varchar(50) not null,
  symptoms text not null,
  disease varchar(100),
  risk_level varchar(20),
  treatment text,
  synced boolean default true,
  created_at timestamptz default now()
);

create table if not exists public.health_index (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  crop_score double precision not null,
  soil_score double precision not null,
  water_score double precision not null,
  livestock_score double precision not null,
  machinery_score double precision not null,
  fhi_score double precision not null,
  synced boolean default true,
  created_at timestamptz default now()
);

create table if not exists public.sync_queue (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  module varchar(50) not null,
  payload jsonb not null,
  synced boolean default false,
  created_at timestamptz default now()
);

create index if not exists idx_crop_scans_user_id on public.crop_scans(user_id);
create index if not exists idx_livestock_recs_user_id on public.livestock_recs(user_id);
create index if not exists idx_health_index_user_id on public.health_index(user_id);
create index if not exists idx_sync_queue_user_id on public.sync_queue(user_id);
create index if not exists idx_sync_queue_synced on public.sync_queue(synced);
create index if not exists idx_crop_scans_created_at on public.crop_scans(created_at desc);
create index if not exists idx_livestock_recs_created_at on public.livestock_recs(created_at desc);
create index if not exists idx_health_index_created_at on public.health_index(created_at desc);

alter table public.profiles enable row level security;
alter table public.crop_scans enable row level security;
alter table public.livestock_recs enable row level security;
alter table public.health_index enable row level security;
alter table public.sync_queue enable row level security;

drop policy if exists "profiles_select_own" on public.profiles;
drop policy if exists "profiles_insert_own" on public.profiles;
drop policy if exists "profiles_update_own" on public.profiles;
drop policy if exists "crop_scans_own_all" on public.crop_scans;
drop policy if exists "livestock_recs_own_all" on public.livestock_recs;
drop policy if exists "health_index_own_all" on public.health_index;
drop policy if exists "sync_queue_own_all" on public.sync_queue;

create policy "profiles_select_own"
on public.profiles
for select
using (auth.uid() = id);

create policy "profiles_insert_own"
on public.profiles
for insert
with check (auth.uid() = id);

create policy "profiles_update_own"
on public.profiles
for update
using (auth.uid() = id)
with check (auth.uid() = id);

create policy "crop_scans_own_all"
on public.crop_scans
for all
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create policy "livestock_recs_own_all"
on public.livestock_recs
for all
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create policy "health_index_own_all"
on public.health_index
for all
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create policy "sync_queue_own_all"
on public.sync_queue
for all
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, name, email)
  values (
    new.id,
    coalesce(new.raw_user_meta_data ->> 'name', 'New User'),
    new.email
  )
  on conflict (id) do nothing;

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;

create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();
